version: "3.9"
services:
  bot:
    build: ./docker
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "${METRICS_PORT}:${METRICS_PORT}"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - ./kuma:/app/data
    ports:
      - "3001:3001"
    restart: always
    profiles:
      - kuma

  alert-bot:
    build: ./docker
    command: ["python", "-m", "alert_bot.app"]
    env_file: .env
    restart: always
    profiles:
      - monitoring
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    profiles:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    profiles:
      - monitoring
