version: "3.9"
services:
  bot:
    build: ./docker
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - ./kuma:/app/data
    ports:
      - "3001:3001"
    restart: always
    profiles:
      - kuma
